TRAIN:
  ENABLE: True
  DATASET: Ego4dRecognition
  BATCH_SIZE: 64
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224 
  INPUT_CHANNEL_NUM: [3, 3] 
  TASK: "classification"
  TARGET_FPS: 30
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True # Needs to be true for loading in model 
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE: [[0, 1, 8, 8], [1, 1, 4, 4], [2, 1, 4, 4], [3, 1, 2, 2], [4, 1, 2, 2], [5, 1, 2, 2], [6, 1, 2, 2], [7, 1, 2, 2], [8, 1, 2, 2], [9, 1, 2, 2], [10, 1, 2, 2], [11, 1, 2, 2], [12, 1, 2, 2], [13, 1, 2, 2]]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
SOLVER:
  BASE_LR: 1e-2
  LR_POLICY: cosine_warmup
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: sgd
  WEIGHT_DECAY: 1e-4
MODEL:
  NUM_CLASSES: [115, 478]
  ARCH: mvit
  MODEL_NAME: MultiTaskMViT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  MULTI_INPUT_FEATURES: 2048 
TEST:
  ENABLE: True
  DATASET: Ego4dRecognition
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .