TRAIN:
  ENABLE: True
  DATASET: Ego4dShortTermAnticipation
  BATCH_SIZE: 32
CHECKPOINT_FILE_PATH: pretrained_models/SLOWFAST_8x8_R50.pkl
CHECKPOINT_VERSION: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  TASK: short_term_anticipation
  TARGET_FPS: 30
DETECTION:
  ALIGNED: True
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: sgd
  WEIGHT_DECAY: 1e-4
MODEL:
  NUM_VERBS: 74
  NUM_NOUNS: 87
  ARCH: slowfast
  MODEL_NAME: ShortTermAnticipationSlowFast
  VERB_LOSS_FUNC: cross_entropy
  TTC_LOSS_FUNC: smooth_l1
  STA_LOSS_WEIGHTS: [1, 10] #verb, TTC
  DROPOUT_RATE: 0.8
  HEAD_VERB_ACT: softmax
  HEAD_TTC_ACT: softplus
TEST:
  ENABLE: True
  DATASET: Ego4dShortTermAnticipation
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /mnt/cache/xingsen/ego4d/short_term_anticipation/models/slowfast_model/
